spring:
  application:
    name: item-service
  mail:
    host: smtp.163.com #发送邮件服务器
    username: ZhangxfSy@163.com #163邮箱
    password: lsyandzxf931227 #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或994
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ZhangxfSy@163.com #与上面的username保持一致
    
#server:
#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      

ring:
  profiles: item-service1

server:
  port: 8001

---
spring:
  profiles: item-service2

server:
  port: 8002